version: '3.1'

services:
  app:
    build: video
    restart: always
    depends_on:
      - postgres
    ports:
      - "5055:5005"
    environment:
      - SQLALCHEMY_DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
  postgres:
    image: postgres:10
    restart: always
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASWORD}
